In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.2'

In [3]:
import math as matematica

In [5]:
matematica.ceil(3.1)

4

In [6]:
numere = [1, 2, 3, 4, 5]
print(numere, type(numere))

[1, 2, 3, 4, 5] <class 'list'>


In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [9]:
t = (1, 2, 3, 4, 5)
arr = np.array(t)
arr, type(arr)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [10]:
r = range(3, 8)
arr = np.array(r)
arr, type(arr)

(array([3, 4, 5, 6, 7]), numpy.ndarray)

In [14]:
colectie = ["iarna", "vara", "toamna"]
arr = np.array(colectie)
print("arr=", arr)
print("type(arr)", type(arr))
print("dtype =", arr.dtype)


arr= ['iarna' 'vara' 'toamna']
type(arr) <class 'numpy.ndarray'>
dtype = <U6


In [15]:
r = range(3, 8)
arr = np.array(r)
arr, type(arr), arr.dtype

(array([3, 4, 5, 6, 7]), numpy.ndarray, dtype('int64'))

In [16]:
2 ** 8

256

In [18]:
arr = np.array([20, 30, 40])
arr, arr.dtype

(array([20, 30, 40]), dtype('int64'))

In [19]:
arr = np.array([20, 30, 40], dtype=np.int8)
arr, arr.dtype

(array([20, 30, 40], dtype=int8), dtype('int8'))

In [20]:
arr = np.array([20, 30, 40, 127], dtype=np.int8)
arr, arr.dtype

(array([ 20,  30,  40, 127], dtype=int8), dtype('int8'))

In [22]:
arr = np.array([20, 30, 40, -100], dtype=np.int8)
arr, arr.dtype

(array([  20,   30,   40, -100], dtype=int8), dtype('int8'))

In [23]:
arr = np.array([20, 30, 40, -128], dtype=np.int8)
arr, arr.dtype

(array([  20,   30,   40, -128], dtype=int8), dtype('int8'))

In [25]:
arr = np.array([20, 30, 40, -128], dtype=np.int8)
arr, arr.dtype

(array([  20,   30,   40, -128], dtype=int8), dtype('int8'))

In [28]:
arr = np.array([20, 30, 40, 255], dtype=np.uint8)
arr, arr.dtype

(array([ 20,  30,  40, 255], dtype=uint8), dtype('uint8'))