In [1]:
import numpy as np

In [2]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [5]:
np.arange(5, 11, 2)

array([5, 7, 9])

In [10]:
arr = np.arange(5, 11, 2)
print(arr )
print("max=", arr.max())
print("min=", arr.min())
print("len=", arr.size)


[5 7 9]
max= 9
min= 5
len= 3


In [11]:
arr = np.arange(5, 11, 2)
print(arr )
print("max=", max(arr))
print("min=", min(arr))
print("len=", len(arr))

[5 7 9]
max= 9
min= 5
len= 3


In [14]:
arr = np.arange(5, 11, 2)
print(arr )
print("argmax=", arr.argmax())
print("argmin=", arr.argmin())



[5 7 9]
argmax= 2
argmin= 0


In [16]:
arr = np.arange(10, 100, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [17]:
arr = np.arange(10, 100, 5)
arr[:5]

array([10, 15, 20, 25, 30])

In [18]:
arr = np.arange(10, 100, 5)
arr[:5:2]

array([10, 20, 30])

In [21]:
arr = np.arange(1, 10)
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr = np.arange(1, 10)
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [25]:
arr = np.arange(1, 10)
arr / 2
print(arr)

[1 2 3 4 5 6 7 8 9]


In [26]:
arr = np.arange(1, 10)
arr = arr / 2
print(arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [28]:
arr = np.arange(1, 10) 
arr > 2, arr

(array([False, False,  True,  True,  True,  True,  True,  True,  True]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [29]:
arr = range(1, 10) 
list(map(lambda x: x>2, arr))

[False, False, True, True, True, True, True, True, True]

In [30]:
arr = range(1, 10) 
list(filter(lambda x: x>2, arr))

[3, 4, 5, 6, 7, 8, 9]

In [31]:
arr = np.arange(1, 10) 
arr[arr > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = np.arange(1, 10) 
print(arr)
arr % 3 != 0


[1 2 3 4 5 6 7 8 9]


array([ True,  True, False,  True,  True, False,  True,  True, False])

In [39]:
arr = np.arange(1, 10) 
print(arr)
arr[arr % 3 != 0]

[1 2 3 4 5 6 7 8 9]


array([1, 2, 4, 5, 7, 8])

In [41]:
arr = np.arange(1, 10) 
print(arr)
arr[arr % 3 == 0]

[1 2 3 4 5 6 7 8 9]


array([3, 6, 9])

In [44]:
arr = np.arange(1, 10) 
print(arr)
arr[(arr % 3 != 0) & (arr > 5)]

[1 2 3 4 5 6 7 8 9]


array([7, 8])

In [45]:
arr = np.arange(1, 10) 
print(arr)
nedivizibile_cu_3 =  arr % 3 != 0
mai_mari_ca_5 = arr > 5
arr[nedivizibile_cu_3 & mai_mari_ca_5]

[1 2 3 4 5 6 7 8 9]


array([7, 8])

In [47]:
arr = np.arange(1, 10) 
print(arr)
nedivizibile_cu_3 =  arr % 3 != 0
mai_mari_ca_5 = arr > 5
arr[nedivizibile_cu_3 | mai_mari_ca_5]

[1 2 3 4 5 6 7 8 9]


array([1, 2, 4, 5, 6, 7, 8, 9])