In [1]:
import numpy as np

In [2]:

# %%
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 0.

np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.full(10, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.full(10, 7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [5]:
np.full(4, 22)

array([22, 22, 22, 22])

In [6]:
######### Exercitiul ################
# Creați un vector cu 10 elemente întregi, toate fiind egale cu 1.
np.ones(10)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9.


np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 10 la 29.

np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [10]:
######### Exercitiul ################
# Creați un vector cu elemente întregi de la 0 la 9 în ordine inversă.

np.arange(10)[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
np.array(list(reversed(np.arange(10))))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [17]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
######### Exercitiul ################
# Creați un vector cu 10 elemente aleatoare între 0 și 1.

np.random.rand()


0.5906004839505502

In [19]:
np.random.rand(10)

array([0.6823873 , 0.4168138 , 0.32633397, 0.0588028 , 0.5384641 ,
       0.49592489, 0.65018981, 0.65873487, 0.28240336, 0.7425462 ])

In [21]:
np.random.random()

0.5634328628293708

In [27]:

np.random.seed(42)


In [25]:
np.random.random(10)

array([0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041])

In [28]:
######### Exercitiul ################
# Creați o matrice 3x3 cu elemente întregi aleatoare între 0 și 9.
np.random.randint(0, 10, (3, 3))


array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [30]:
######### Exercitiul ################
# Creați o matrice identitate 5x5.
np.eye(3)




array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
######### Exercitiul ################
# Adunați două matrici de dimensiuni egale (de exemplu, 3x3).
m1 = np.random.randint(0, 10, (3, 3))
m2 = np.random.randint(0, 10, (3, 3))
print(m1) 
print(m2) 
print(m1 + m2)

[[8 6 1]
 [3 8 1]
 [9 8 9]]
[[4 1 3]
 [6 7 2]
 [0 3 1]]
[[12  7  4]
 [ 9 15  3]
 [ 9 11 10]]


In [36]:
######### Exercitiul ################
# Înmulțiți două matrici de dimensiuni corespunzătoare (de  exemplu, 2x3 și 3x2).

m1 = np.random.randint(0, 10, (2, 3))
m2 = np.random.randint(0, 10, (2, 3))
print("m1=", m1) 
print("m2=", m2) 
print("m1 * m2=",m1 * m2)


m1= [[0 8 6]
 [8 7 0]]
m2= [[7 7 2]
 [0 7 2]]
m1 * m2= [[ 0 56 12]
 [ 0 49  0]]


In [37]:

m1 = np.random.randint(0, 10, (2, 3))
m2 = np.random.randint(0, 10, (3, 2))
print("m1=", m1) 
print("m2=", m2) 
print("m1 * m2=",np.dot(m1, m2))

m1= [[2 0 4]
 [9 6 9]]
m2= [[8 6]
 [8 7]
 [1 0]]
m1 * m2= [[ 20  12]
 [129  96]]


In [39]:
######### Exercitiul ################
# Transpuneți o matrice (de exemplu, 3x4).

m1 = np.random.randint(0, 10, (1, 5))
m1


array([[7, 5, 2, 0, 2]])

In [40]:
m1.T

array([[7],
       [5],
       [2],
       [0],
       [2]])

In [41]:
######### Exercitiul ################
# Găsiți valoarea maximă dintr-un vector.
arr = np.random.randint(0, 10, (1, 5))
print(arr, arr.max())


[[4 2 0 4 9]] 9


In [45]:
######### Exercitiul ################
# Găsiți indicele valorii maxime dintr-un vector.
arr = np.random.randint(0, 10, (1, 5))
print(arr, arr.argmax())


[[2 5 1 9 8]] 3


In [48]:
######### Exercitiul ################
# Găsiți media aritmetică a valorilor dintr-o matrice.
arr = np.random.randint(0, 5, 10)
print(arr, np.mean(arr))

[3 3 3 3 2 1 3 0 0 0] 1.8


In [49]:
arr = np.random.randint(0, 5, 10)
print(arr, arr.mean())

[0 2 0 3 4 0 2 2 0 4] 1.7
